#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
      register: terraform

    - name: add terraform zabbix_web host to inventory
      add_host:
        name: "{{ terraform.outputs.zabbix_web.value }}"
        groups:
           - zabbix_web

    - name: add terraform zabbix_server host to inventory
      add_host:
        name: "{{ terraform.outputs.zabbix_server.value }}"
        groups:
           - zabbix_server

    - name: add terraform mysql_server host to inventory
      add_host:
        name: "{{ terraform.outputs.mysql_server.value }}"
        groups:
           - mysql_server

- name: setup shared resources
  hosts: all
  become: yes
  gather_facts: no
  remote_user: root

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.common
    - role: robertdebock.firewall
    - role: robertdebock.epel
    - role: robertdebock.rsyslog
    - role: robertdebock.postfix
    - role: robertdebock.digitalocean_agent
    - role: robertdebock.zabbix_repository
    - role: robertdebock.zabbix_agent

- name: setup mysql_server resources
  hosts: mysql_server
  become: yes
  gather_facts: yes
  remote_user: root

  roles:
    - role: robertdebock.mysql

- name: setup zabbix_server and zabbix_web resources
  hosts: zabbix_server:zabbix_web
  become: yes
  gather_facts: yes
  remote_user: root

  roles:
    - role: robertdebock.buildtools
    - role: robertdebock.selinux
    - role: robertdebock.software

- name: setup zabbix_server resources
  hosts: zabbix_server
  become: yes
  gather_facts: yes
  remote_user: root

  roles:
    - role: robertdebock.zabbix_server

- name: setup zabbix_web resources
  hosts: zabbix_web
  become: yes
  gather_facts: yes
  remote_user: root

  roles:
    - role: robertdebock.core_dependencies
    - role: robertdebock.python_pip
    - role: robertdebock.openssl
    - role: robertdebock.httpd
    - role: robertdebock.php
    - role: robertdebock.zabbix_web
    - role: robertdebock.certbot
